title: "Wael Rahhal"
email: waelr1985@gmail.com
description: "AI Consultant • Data Scientist • Ph.D. Business Management"
baseurl: ""
url: "https://waelr1985.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

author:
  name   : "Wael Rahhal"
  avatar : "/assets/img/profile.jpg"
  bio    : "MSc Data Science • Ph.D. Business • AI/ML Consultant"
  location: "Istanbul, Turkey | Dubai, UAE"

header:
  image: "/assets/img/banner.jpg"
  caption: "AI + Data Science = Smart Decisions"

navigation:
  enabled: true
